import mpmath
from mpmath import mp
from dataclasses import dataclass
from typing import List, Optional, Dict, Any, Callable
from agents.galois.pslq_reduction import PSLQReductionWorker

@dataclass
class PSLQResult:
    found: bool
    relation: Optional[List[int]] = None
    residual: Optional[float] = None
    confidence: Optional[str] = None
    basis_labels: Optional[List[str]] = None


class PSLQLeafEvaluator:
    def __init__(self, dps: int = 500, basis_registry: Optional[Dict[str, List[Callable]]] = None):
        self.dps = dps
        self.worker = PSLQReductionWorker(dps=self.dps)
        self.basis_registry = basis_registry or {}

    def evaluate_candidate(self, target: mp.mpf, candidate_expr: str, domain: Optional[str] = None) -> PSLQResult:
        """
        Evaluate a candidate mathematical expression against the target.
        Uses multi-pass PSLQ (additive, multiplicative, full).
        """
        try:
            # Safely evaluate the candidate expression string.
            # In a real environment, this should be parsed or evaluated securely.
            # Here we just use mpmath.mp.mpf or sympify (we'll assume evaluateable by mpmath)
            # For this implementation, we will use a basic eval with mpmath context
            # because the expressions are generated by the LLM in MCTS.
            context = mpmath.__dict__.copy()
            candidate_val = eval(candidate_expr, context)
            if not isinstance(candidate_val, mp.mpf):
                candidate_val = mp.mpf(candidate_val)
        except Exception:
            return PSLQResult(found=False)

        # Pass A: Additive
        res_a = self.worker.hunt_linear(target, candidate_val)
        if res_a["found"] and res_a["confidence_drop"]:
            return PSLQResult(
                found=True,
                relation=res_a["relation"],
                residual=res_a["residual"],
                confidence="EXACT",
                basis_labels=res_a["vector"]
            )

        # Pass B: Multiplicative
        res_b = self.worker.hunt_logarithmic(target, candidate_val)
        if res_b["found"] and res_b["confidence_drop"]:
            return PSLQResult(
                found=True,
                relation=res_b["relation"],
                residual=res_b["residual"],
                confidence="EXACT",
                basis_labels=res_b["vector"]
            )

        # Pass C: Full (if domain is provided)
        if domain and domain in self.basis_registry:
            basis_fns = self.basis_registry[domain]
            # First element is target, second is candidate, rest from registry
            basis_values = [target, candidate_val] + [fn() for fn in basis_fns[2:]]
            basis_labels = ["target", "candidate"] + [fn.__name__ for fn in basis_fns[2:]]
            
            res_c = self.worker.hunt_full(target, candidate_val, basis_labels, basis_values)
            if res_c["found"] and res_c["confidence_drop"]:
                return PSLQResult(
                    found=True,
                    relation=res_c["relation"],
                    residual=res_c["residual"],
                    confidence="EXACT",
                    basis_labels=res_c["vector"]
                )

        return PSLQResult(found=False)
