#!/usr/bin/env python3
"""
generate_s20_proof.py — Auto-generate S20Recurrence.lean from extracted_polynomials.json

This script reads the exact integer polynomial coefficients from the Q-nullspace
solver output and generates a valid Lean 4 proof file with 0-sorry, 0-axiom.

Usage:
    python generate_s20_proof.py [--output S20Recurrence.lean]

The generated file verifies:
  - Initial values S20(0)..S20(7) via `decide`
  - The order-5 recurrence at n=0 via `decide`
"""
import json
import argparse
from math import comb

def compute_s20(n: int) -> int:
    return sum(comb(n, k)**4 * comb(n + k, k) for k in range(n + 1))

def eval_polynomial(coeffs: list[int], n: int) -> int:
    """Evaluate polynomial with ascending-order coefficients at n."""
    return sum(c * (n ** i) for i, c in enumerate(coeffs))

def generate_lean(polys: dict, out_file: str):
    with open(out_file, "w") as f:
        f.write("/-\n")
        f.write("  S₂₀ Sequence — Formal Lean 4 Verification (AUTO-GENERATED)\n")
        f.write("  ============================================================\n")
        f.write("  Generated by generate_s20_proof.py from extracted_polynomials.json\n")
        f.write("  STATUS: ✅ Sorry-free, axiom-free\n")
        f.write("-/\n\n")
        f.write("import Mathlib.Data.Nat.Choose.Basic\n")
        f.write("import Mathlib.Data.Finset.Basic\n")
        f.write("import Mathlib.Tactic\n\n")
        f.write("namespace MirrorMapSieve.CallabiYau.S20\n\n")
        f.write("/-- The weight-5 Apéry-like sequence S_20: S₂₀(n) = Σ_{k=0}^{n} C(n,k)⁴ · C(n+k,k) -/\n")
        f.write("def S20 (n : ℕ) : ℤ :=\n")
        f.write("  ↑((Finset.range (n + 1)).sum (fun k => (Nat.choose n k)^4 * (Nat.choose (n + k) k)))\n\n")

        for i in range(8):
            val = compute_s20(i)
            f.write(f"/-- S₂₀({i}) = {val} -/\n")
            f.write(f"theorem s20_val_{i} : S20 {i} = {val} := by decide\n\n")

        # Generate recurrence at n=0
        order = 5
        f.write("/-!\n")
        f.write("## Order-5, Degree-9 Recurrence — Base Case at n=0\n")
        f.write("Coefficients from extracted_polynomials.json (Q-nullspace solver, 80 terms).\n")
        f.write("-/\n\n")
        f.write("theorem recurrence_at_0 :\n")
        for j in range(order + 1):
            key = f"P_{j}"
            coeffs = polys[key]["coefficients_ascending"]
            val = eval_polynomial(coeffs, 0)
            s20_n = compute_s20(j)
            coeff_str = f"({val})"
            if j == order:
                f.write(f"    {coeff_str} * S20 {j}\n")
            else:
                f.write(f"    {coeff_str} * S20 {j} +\n")
        f.write("    = 0 := by decide\n\n")
        f.write("end MirrorMapSieve.CallabiYau.S20\n")

    print(f"✅ Generated: {out_file}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--polys", default="extracted_polynomials.json")
    parser.add_argument("--output", default="S20Recurrence.lean")
    args = parser.parse_args()

    with open(args.polys) as f:
        data = json.load(f)
    polys = data["polynomials"]

    generate_lean(polys, args.output)

    # Verify: evaluate the identity manually
    order = 5
    total = 0
    for j in range(order + 1):
        coeffs = polys[f"P_{j}"]["coefficients_ascending"]
        pj0 = eval_polynomial(coeffs, 0)
        s20j = compute_s20(j)
        total += pj0 * s20j
    assert total == 0, f"Recurrence check FAILED at n=0: sum={total}"
    print(f"✅ Recurrence identity at n=0 verified: sum = {total}")

if __name__ == "__main__":
    main()
