import base64
from pydantic import BaseModel, Field, field_validator, model_validator

class ContextBindingError(ValueError):
    """Raised when an agent generates a generic mock instead of problem-specific logic."""
    pass

class Lean4Sketch(BaseModel):
    """Wraps Lean 4 code in Base64 to prevent JSON serialization/newline truncation."""
    code_base64: str

    @property
    def decoded_code(self) -> str:
        return base64.b64decode(self.code_base64).decode('utf-8')

    @classmethod
    def encode(cls, raw_code: str) -> "Lean4Sketch":
        encoded = base64.b64encode(raw_code.encode('utf-8')).decode('utf-8')
        return cls(code_base64=encoded)

class ConjecturePayload(BaseModel):
    problem_id: str
    statement: str = Field(..., description="The mathematical conjecture generated by Galois")
    lean4_sketch: Lean4Sketch

    @field_validator('statement')
    @classmethod
    def forbid_galois_mocks(cls, v: str) -> str:
        # 🚨 HOTFIX: Block the specific manifold/Lie group hallucination
        forbidden_phrases = ["Aut(S) ≅ G", "GL(n, ℝ)", "solution manifold"]
        for phrase in forbidden_phrases:
            if phrase in v:
                raise ContextBindingError(f"Galois Mock Leak Detected! Statement contained forbidden phrase: '{phrase}'")
        return v

    @model_validator(mode='after')
    def forbid_euler_mocks(self) -> "ConjecturePayload":
        # 🚨 HOTFIX: Block the Pythagore dummy template
        code = self.lean4_sketch.decoded_code
        if "theorem add_zero" in code:
            raise ContextBindingError("Euler Mock Leak Detected! 'add_zero' dummy proof found in Lean AST.")
        return self
