# Copyright (c) 2026 Xavier Callens / Socrate AI Lab
# Licensed under Apache 2.0 - see LICENSE file
"""Lean 4 Code Generator — IR → Lean 4 StateT Monad Output.

Translates the Bourbaki IR (parsed functions + state variables) into
a complete Lean 4 file with:
  1. A structure for the contract state
  2. StateT monad functions for each transition
  3. Security theorem stubs with sorry gaps for Galois

Reference: 🏛️ SPECIFICATION: The Bourbaki Translation Layer v21.
Patent: US-PAT-PEND-2026-0525
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import structlog

from agents.bourbaki.codegen.type_mapper import TypeMapper

if TYPE_CHECKING:
    from agents.bourbaki.agent import BourbakiIR

logger = structlog.get_logger(__name__)


class LeanCodeGenerator:
    """Generates Lean 4 source code from a BourbakiIR.

    Produces:
      - Import headers
      - A Lean 4 structure for the contract state
      - StateT monad transition functions
      - Security theorems with sorry gaps
    """

    def __init__(self, type_mapper: TypeMapper) -> None:
        self._type_mapper = type_mapper
        self._log = logger.bind(component="lean_codegen")

    def generate(self, ir: BourbakiIR) -> tuple[str, list[str], list[str]]:
        """Generate complete Lean 4 file from IR.

        Args:
            ir: The Bourbaki intermediate representation.

        Returns:
            Tuple of (lean_code, theorem_names, diagnostics).
        """
        diagnostics: list[str] = []
        theorems: list[str] = []
        sections: list[str] = []

        # Header
        sections.append(self._gen_header(ir))

        # State structure
        sections.append(self._gen_state_structure(ir))

        # Transition functions
        for func in ir.functions:
            sections.append(self._gen_transition_function(func, ir))

        # Security theorems
        for func in ir.functions:
            theorem_code, theorem_name = self._gen_security_theorem(func, ir)
            sections.append(theorem_code)
            theorems.append(theorem_name)

        # Compose full file
        lean_code = "\n\n".join(sections) + "\n"

        # Validate basic structure
        if not ir.state_fields:
            diagnostics.append(
                "WARNING: No state variables detected. "
                "The contract may be stateless or parsing incomplete."
            )

        if not ir.functions:
            diagnostics.append(
                "WARNING: No functions detected. "
                "Check the parser or source code format."
            )

        self._log.info(
            "lean_generated",
            lines=lean_code.count("\n"),
            theorems=len(theorems),
        )
        return lean_code, theorems, diagnostics

    # ------ Section Generators ---------------------------------------------

    def _gen_header(self, ir: BourbakiIR) -> str:
        """Generate import headers and module preamble."""
        return (
            f"-- =============================================================\n"
            f"-- Auto-generated by Bourbaki Translation Layer\n"
            f"-- Source: {ir.source_language} contract '{ir.contract_name}'\n"
            f"-- GALOIS MCTS ENGINE TAKES OVER AT sorry GAPS\n"
            f"-- =============================================================\n"
            f"\n"
            f"import Mathlib.Tactic\n"
            f"import Mathlib.Data.Nat.Basic\n"
            f"\n"
            f"open Nat\n"
            f"\n"
            f"namespace Bourbaki.{ir.contract_name}"
        )

    def _gen_state_structure(self, ir: BourbakiIR) -> str:
        """Generate the Lean 4 structure for the contract state."""
        if not ir.state_fields:
            return (
                f"-- No state variables detected\n"
                f"structure {ir.contract_name}State where\n"
                f"  dummy : Unit := ()"
            )

        lines = [f"structure {ir.contract_name}State where"]
        for var_name, lean_type in ir.state_fields.items():
            clean_name = self._sanitize_name(var_name)
            lines.append(f"  {clean_name} : {lean_type}")
        lines.append(f"  deriving Repr")

        return "\n".join(lines)

    def _gen_transition_function(self, func, ir: BourbakiIR) -> str:
        """Generate a StateT monad function for a parsed function."""
        func_name = self._sanitize_name(func.name)
        state_type = f"{ir.contract_name}State"

        # Build parameter list
        param_parts = []
        for pname, ptype in func.params.items():
            lean_type = self._type_mapper.map_type(ptype, ir.source_language)
            clean_name = self._sanitize_name(pname)
            param_parts.append(f"({clean_name} : {lean_type})")

        params_str = " ".join(param_parts) if param_parts else ""

        # Build function body with preconditions and state mutations
        lines = [
            f"/-- Bourbaki-translated '{func.name}' from {ir.source_language}. -/",
            f"def {func_name} {params_str} : "
            f"StateT {state_type} (Except String) Unit := do",
            f"  let s ← get",
        ]

        # Preconditions → guard clauses
        for precond in func.preconditions:
            clean_cond = self._translate_condition(precond, ir.source_language)
            lines.append(f"  if ¬({clean_cond}) then throw \"{precond}\"")

        # State mutations → set
        if func.state_writes:
            updates = []
            for var_name in func.state_writes:
                clean_name = self._sanitize_name(var_name)
                updates.append(f"{clean_name} := s.{clean_name}")
            # Simplified: we note where the mutation happens
            updates_str = ", ".join(updates)
            lines.append(f"  -- State mutation: {', '.join(func.state_writes.keys())}")
            lines.append(f"  set {{ s with {updates_str} }}")
        else:
            lines.append(f"  pure ()")

        return "\n".join(lines)

    def _gen_security_theorem(self, func, ir: BourbakiIR) -> tuple[str, str]:
        """Generate a security theorem stub with a sorry gap.

        Returns:
            Tuple of (theorem_code, theorem_name).
        """
        func_name = self._sanitize_name(func.name)
        state_type = f"{ir.contract_name}State"
        theorem_name = f"{func_name}_safe"

        # Build parameter bindings for the theorem
        param_bindings = []
        for pname, ptype in func.params.items():
            lean_type = self._type_mapper.map_type(ptype, ir.source_language)
            clean_name = self._sanitize_name(pname)
            param_bindings.append(f"({clean_name} : {lean_type})")

        params_str = " ".join(param_bindings) if param_bindings else ""

        # Generate the security invariant
        # Default: function execution does not produce an error state
        theorem_code = (
            f"/-- Security invariant: '{func.name}' preserves contract integrity. -/\n"
            f"theorem {theorem_name} (s : {state_type}) {params_str} :\n"
            f"  ∃ s', ({func_name} {' '.join(self._sanitize_name(p) for p in func.params)}).run s = .ok ((), s') := by\n"
            f"  sorry -- GALOIS MCTS TAKES OVER HERE"
        )

        return theorem_code, theorem_name

    # ------ Utilities -------------------------------------------------------

    def _sanitize_name(self, name: str) -> str:
        """Sanitize a source-language identifier for Lean 4.

        Replaces invalid characters and avoids Lean 4 keywords.
        """
        LEAN_KEYWORDS = {
            "def", "theorem", "lemma", "let", "do", "if", "then", "else",
            "match", "where", "have", "show", "by", "sorry", "import",
            "open", "namespace", "end", "structure", "class", "instance",
            "set", "get", "pure", "return",
        }

        # Replace dots and dashes with underscores
        clean = name.replace(".", "_").replace("-", "_")

        # Prefix keywords
        if clean in LEAN_KEYWORDS:
            clean = f"{clean}_v"

        return clean

    def _translate_condition(
        self, condition: str, language: str
    ) -> str:
        """Translate a source-language boolean condition to Lean 4 syntax.

        This is a best-effort translation for common patterns.
        Complex conditions should be manually reviewed.

        Args:
            condition: Source-language boolean expression.
            language: Source language identifier.

        Returns:
            Lean 4 boolean expression string.
        """
        # Common Solidity patterns
        result = condition
        result = result.replace(">=", "≥")
        result = result.replace("<=", "≤")
        result = result.replace("!=", "≠")
        result = result.replace("==", "=")
        result = result.replace("&&", "∧")
        result = result.replace("||", "∨")
        result = result.replace("!", "¬")
        result = result.replace("msg.sender", "sender")

        # Replace state variable access
        # balance → s.balance
        result = result.replace("balance", "s.balance")

        return result
