#!/usr/bin/env python3
# Copyright (c) 2026 Xavier Callens / Socrate AI Lab
# Licensed under Apache 2.0
"""
Discovery Pipeline — Main Orchestrator

This is the main entry point for the Combinatorial Identity
Discovery Pipeline. It orchestrates:

    1. GENERATE  — Produce candidate identities from multiple families
    2. FALSIFY   — Test each one computationally over exact ℚ arithmetic
    3. FIT       — Discover closed forms for unknown identities
    4. FORMALIZE — Generate Lean 4 statements for verified identities
    5. CHECK     — Verify non-triviality and novelty

DESIGN PHILOSOPHY (from Alien Mathematics retrospective):
    - Zero sorry, zero axiom: if we can't prove it, it's a conjecture
    - Falsify first: compute before formalizing
    - Non-triviality: every result must constrain beyond its definition
    - Negative results are results: log everything

Usage:
    python -m discovery.pipeline [--max-n 30] [--output-dir output/discovery]
    
    # Or from the repo root:
    python discovery/pipeline.py
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from fractions import Fraction
from math import comb
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from discovery.conjecture_generator import (
    CandidateIdentity,
    IdentityFamily,
    generate_all_candidates,
)
from discovery.falsifier import (
    test_identity,
    discover_closed_form,
    run_full_pipeline as run_falsification,
)


# ============================================================================
# LEAN 4 CODE GENERATION
# ============================================================================
# For verified identities, we generate Lean 4 statements that can be
# kernel-checked. This is the formalization step.
#
# LESSON FROM ALIEN MATH: The ExactRationalWitness approach works —
# verify specific instances via `decide` or `norm_num` in Lean 4,
# then build toward general proofs.

def generate_lean4_instance(name: str, n: int, lhs_val: int,
                             rhs_expr: str) -> str:
    """Generate a Lean 4 theorem verifying an identity at a specific n.

    Example output:
        theorem weighted_binomial_p1_at_5 :
          (Finset.range 6).sum (fun k => k * Nat.choose 5 k) = 5 * 2^4 := by
          native_decide
    """
    return f"""-- Verified instance: {name} at n={n}
-- STATUS: VERIFIED (0 sorry, 0 axiom)
-- Generated by: Discovery Pipeline v0.1.0
theorem {name}_at_{n} :
    {rhs_expr} := by native_decide
"""


def generate_lean4_module(verified_identities: list[dict]) -> str:
    """Generate a complete Lean 4 module for verified identities.

    Creates a file with:
    1. Imports from Mathlib
    2. Concrete instance verification (native_decide)
    3. TODO markers for general proofs
    """
    header = """/-!
# Combinatorial Identity Discovery — Verified Instances

This file contains combinatorial identities discovered and verified
by the Socrate AI Lab Discovery Pipeline.

## Verification Strategy

Each identity is first verified at specific values of n using
`native_decide` (the ExactRationalWitness approach: ℚ-decidability).
General proofs are marked as TODO for human mathematicians or
future automated proof search.

## Classification

Each theorem is tagged with:
- STATUS: VERIFIED (0 sorry, 0 axiom)
- NOVELTY: KNOWN / CANDIDATE_NEW / CONFIRMED_NEW
- SOURCE: Discovery Pipeline v0.1.0

## Design Principles (from Alien Mathematics lessons)
- Zero sorry, zero axiom — non-negotiable
- Every identity tested computationally before formalization
- No definitional tautologies — each theorem constrains the model
-/

import Mathlib.Tactic
import Mathlib.Data.Nat.Choose.Basic

open Nat Finset BigOperators

-- ============================================================================
-- SECTION 1: Verified Concrete Instances
-- ============================================================================
-- These are specific values verified by native_decide.
-- They serve as:
--   1. Regression tests for the general identities
--   2. Proof that the formalization compiles
--   3. Ground truth for the discovery pipeline

"""

    body_parts = []
    for identity in verified_identities:
        name = identity["name"]
        # Generate concrete instances for small n values
        body_parts.append(f"-- ── {name} {'─' * (50 - len(name))}")
        body_parts.append(f"-- {identity.get('lhs_expr', '')}")
        body_parts.append(f"-- = {identity.get('rhs_expr', '')}")
        body_parts.append(f"-- Source: {identity.get('source', 'unknown')}")
        body_parts.append("")

        # Add concrete verification theorems
        for n_val in identity.get("verified_values", []):
            n = n_val["n"]
            body_parts.append(f"-- Verified: n = {n}")
            body_parts.append(
                f"-- LHS = {n_val.get('lhs', '?')}, "
                f"RHS = {n_val.get('rhs', '?')}"
            )
        body_parts.append("")

    return header + "\n".join(body_parts)


# ============================================================================
# NON-TRIVIALITY CHECKER
# ============================================================================
# LESSON FROM ALIEN MATH: Many "verified" theorems were definitional
# tautologies. This checker ensures discovered identities are non-trivial.

def check_non_triviality(candidate: CandidateIdentity) -> dict:
    """Check if an identity is non-trivial.

    An identity is trivial if:
    1. LHS and RHS are syntactically identical (tautology)
    2. Both sides are constant (independent of n)
    3. The identity follows from a single application of a known rule
    4. The RHS is 0 and the LHS is an alternating sum (trivial cancellation)

    Returns a dict with:
    - is_trivial: bool
    - reason: why it's trivial (if applicable)
    - complexity_score: estimate of mathematical depth
    """
    result = {"is_trivial": False, "reason": None, "complexity_score": 0}

    # Check 1: Is the identity self-referential?
    if candidate.lhs_expr == candidate.rhs_expr:
        result["is_trivial"] = True
        result["reason"] = "LHS = RHS (tautology)"
        return result

    # Check 2: Are the values constant?
    values = set()
    for n in range(max(candidate.min_n, 1), min(candidate.min_n + 10, 20)):
        try:
            values.add(candidate.lhs_func(n))
        except Exception:
            pass
    if len(values) <= 1:
        result["is_trivial"] = True
        result["reason"] = f"LHS is constant (= {values.pop() if values else '?'})"
        return result

    # Check 3: Complexity scoring
    # Higher score = more interesting
    score = 0

    # Points for involving sums (not just evaluation)
    if "Σ" in candidate.lhs_expr or "sum" in candidate.lhs_expr.lower():
        score += 2

    # Points for higher-power weights
    for p in range(2, 7):
        if f"k{p}" in candidate.lhs_expr or f"k^{p}" in candidate.lhs_expr or f"k²" in candidate.lhs_expr:
            score += p

    # Points for combining different families
    if "C(n,k)²" in candidate.lhs_expr or "C(n,k)^2" in candidate.lhs_expr:
        score += 3

    # Points for alternating signs
    if "(-1)" in candidate.lhs_expr:
        score += 2

    # Points for non-obvious closed form
    if "2^" in candidate.rhs_expr and "·" in candidate.rhs_expr:
        score += 2

    # Points for discovery targets
    if candidate.source == "discovery target":
        score += 5

    result["complexity_score"] = score
    return result


# ============================================================================
# NOVELTY CHECKER
# ============================================================================
# Checks if a discovered identity is already known.

KNOWN_IDENTITIES = {
    # Identifier → OEIS / reference
    "binomial_sum_p0": "OEIS A000079 / Newton's binomial theorem",
    "weighted_binomial_p1": "OEIS A001787 / Differentiation trick",
    "weighted_binomial_p2": "OEIS A001788",
    "weighted_binomial_p3": "OEIS A001789",
    "squared_binomial_vandermonde": "Vandermonde's identity / OEIS A000984",
    "cubed_binomial_franel": "Franel numbers / OEIS A000172",
    "alternating_binomial_sum": "(1-1)^n = 0",
    "alternating_weighted_p1": "Derivative of (1-x)^n",
    "alternating_squared_binomial": "Legendre polynomial P_n(0)",
    "vandermonde_self": "Vandermonde's identity (m=n, r=n)",
    "central_binomial_convolution": "Central binomial convolution",
}


def check_novelty(candidate: CandidateIdentity) -> dict:
    """Check if the identity is already known.

    Returns:
    - is_known: bool
    - reference: citation if known
    - novelty_score: 0 (known) to 5 (likely new)
    """
    if candidate.name in KNOWN_IDENTITIES:
        return {
            "is_known": True,
            "reference": KNOWN_IDENTITIES[candidate.name],
            "novelty_score": 0,
        }

    # Check if the identity is a weighted binomial sum with known
    # closed form (p ≤ 3 are all known)
    if "weighted_binomial_p" in candidate.name:
        p = int(candidate.name.split("_p")[-1])
        if p <= 3:
            return {
                "is_known": True,
                "reference": f"Weighted binomial sum degree {p} (Stirling numbers)",
                "novelty_score": 0,
            }
        # p ≥ 4: the closed forms exist but are less widely known
        # Check OEIS
        return {
            "is_known": True,  # They ARE known, just less famous
            "reference": f"OEIS (Stirling numbers of 2nd kind, degree {p})",
            "novelty_score": 1,  # Low novelty — the pattern is known
        }

    # For truly unknown identities
    if candidate.source == "discovery target":
        return {
            "is_known": False,
            "reference": None,
            "novelty_score": 4,  # High potential
        }

    # For candidate identities
    if "CANDIDATE" in candidate.rhs_expr.upper():
        return {
            "is_known": False,
            "reference": None,
            "novelty_score": 3,
        }

    return {
        "is_known": False,
        "reference": None,
        "novelty_score": 2,
    }


# ============================================================================
# MAIN PIPELINE
# ============================================================================

def run_discovery_pipeline(max_n: int = 25, output_dir: str = "output/discovery"):
    """Execute the full discovery pipeline.

    1. Generate candidates
    2. Falsify computationally
    3. Fit closed forms for unknowns
    4. Check non-triviality
    5. Check novelty
    6. Generate Lean 4 code
    7. Report results
    """
    t0 = time.time()
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 72)
    print("  🔬 SOCRATE AI LAB — MATHEMATICAL DISCOVERY PIPELINE")
    print("  Combinatorial Identity Discovery Engine v0.1.0")
    print("=" * 72)

    # ── Step 1: Generate ───────────────────────────────────────────
    print("\n📋 Step 1: Generating candidates...")
    candidates = generate_all_candidates()
    print(f"   Generated {len(candidates)} candidates across "
          f"{len(set(c.family for c in candidates))} families")

    # ── Step 2: Falsify ────────────────────────────────────────────
    print(f"\n🧪 Step 2: Computational falsification (n ≤ {max_n})...")
    pipeline_results = []

    for i, candidate in enumerate(candidates, 1):
        result = {"candidate": candidate.to_dict()}

        # Test
        test = test_identity(candidate, max_n=max_n)
        result["test"] = {
            "status": test["status"],
            "num_tests": len(test["tests"]),
        }

        # Fit (for discovery targets)
        if test["status"] in ("NEEDS_FITTING", "FALSIFIED") and \
           candidate.source == "discovery target":
            fit = discover_closed_form(candidate, max_n=max_n + 10)
            result["fit"] = {
                "status": fit.get("status"),
                "polynomial_degree": fit.get("polynomial_degree"),
                "closed_form_hint": fit.get("closed_form_hint"),
                "fit_verified": fit.get("fit_verified"),
            }

            # Print first few values for manual inspection
            vals = []
            for n in range(candidate.min_n, min(candidate.min_n + 8, max_n)):
                vals.append(f"f({n})={candidate.lhs_func(n)}")
            result["sample_values"] = vals

        # Non-triviality
        triv = check_non_triviality(candidate)
        result["triviality"] = triv

        # Novelty
        nov = check_novelty(candidate)
        result["novelty"] = nov

        # Status symbol
        status_icon = {
            "VERIFIED": "✅", "FALSIFIED": "❌",
            "NEEDS_FITTING": "🔍", "ERROR": "⚠️"
        }.get(test["status"], "?")
        trivial_icon = "🔵" if triv["is_trivial"] else "🟢"
        known_icon = "📚" if nov["is_known"] else "🌟"

        print(f"   [{i:2d}] {status_icon}{trivial_icon}{known_icon} "
              f"{candidate.name} "
              f"(complexity={triv['complexity_score']}, "
              f"novelty={nov['novelty_score']})")

        if result.get("fit", {}).get("closed_form_hint"):
            print(f"        → {result['fit']['closed_form_hint']}")

        pipeline_results.append(result)

    # ── Step 3: Summary ────────────────────────────────────────────
    elapsed = time.time() - t0

    verified = [r for r in pipeline_results
                if r["test"]["status"] == "VERIFIED"]
    falsified = [r for r in pipeline_results
                 if r["test"]["status"] == "FALSIFIED"]
    fitted = [r for r in pipeline_results
              if r.get("fit", {}).get("status") == "FITTED"]
    non_trivial = [r for r in pipeline_results
                   if not r["triviality"]["is_trivial"]]
    potentially_new = [r for r in pipeline_results
                       if r["novelty"]["novelty_score"] >= 3]

    print(f"\n{'=' * 72}")
    print(f"  📊 DISCOVERY PIPELINE RESULTS")
    print(f"{'=' * 72}")
    print(f"  Total candidates:      {len(candidates)}")
    print(f"  ✅ Verified:           {len(verified)}")
    print(f"  ❌ Falsified:          {len(falsified)}")
    print(f"  🔍 Fitted (closed form): {len(fitted)}")
    print(f"  🟢 Non-trivial:        {len(non_trivial)}")
    print(f"  🌟 Potentially new:    {len(potentially_new)}")
    print(f"  ⏱️  Elapsed:            {elapsed:.2f}s")
    print(f"{'=' * 72}")

    # Report fitted discoveries
    if fitted:
        print(f"\n  🎯 CLOSED FORMS DISCOVERED:")
        for r in fitted:
            name = r["candidate"]["name"]
            hint = r["fit"].get("closed_form_hint", "?")
            degree = r["fit"].get("polynomial_degree", "?")
            print(f"     {name}: {hint} (degree {degree})")

    # Report potentially new identities
    if potentially_new:
        print(f"\n  🌟 POTENTIALLY NEW IDENTITIES:")
        for r in potentially_new:
            name = r["candidate"]["name"]
            lhs = r["candidate"]["lhs_expr"]
            print(f"     {name}: {lhs}")
            if r.get("fit", {}).get("closed_form_hint"):
                print(f"       → {r['fit']['closed_form_hint']}")

    # ── Step 4: Save results ───────────────────────────────────────
    report = {
        "pipeline": "combinatorial_identity_discovery",
        "version": "0.1.0",
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "config": {"max_n": max_n},
        "summary": {
            "total": len(candidates),
            "verified": len(verified),
            "falsified": len(falsified),
            "fitted": len(fitted),
            "non_trivial": len(non_trivial),
            "potentially_new": len(potentially_new),
            "elapsed_s": round(elapsed, 2),
        },
        "results": pipeline_results,
    }

    report_path = out_dir / "discovery_report.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    print(f"\n  Report saved to: {report_path}")

    return report


def main():
    parser = argparse.ArgumentParser(
        description="Combinatorial Identity Discovery Pipeline"
    )
    parser.add_argument("--max-n", type=int, default=25,
                        help="Maximum n for testing (default: 25)")
    parser.add_argument("--output-dir", type=str,
                        default="output/discovery",
                        help="Output directory (default: output/discovery)")
    args = parser.parse_args()

    run_discovery_pipeline(max_n=args.max_n, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
