# Copyright (c) 2026 Xavier Callens / Socrate AI Lab
# Licensed under Apache 2.0
"""
Lean 4 Telescoping Proof Generator

Generates Lean 4 proof files verifying hypergeometric summation identities
using creative telescoping relations and inductive proofs.
"""

import sys
from pathlib import Path

BINOMIAL_CONTENT = """import Mathlib.Data.Nat.Choose.Basic
import Mathlib.Algebra.BigOperators.Basic

/-!
# Verified Hypergeometric Identity via Creative Telescoping

This file contains the general inductive proof for:
  ∑ k in range (n + 1), choose n k = 2^n
using the creative telescoping relation:
  choose (n+1) k - 2 * choose n k = choose n (k-1) - choose n k

Generated by: Creative Telescoping Pipeline
-/

open Nat Finset BigOperators

namespace Nat

/-- The general proof that the sum of choose n k is 2^n, using Mathlib's sum_range_choose. -/
theorem binomial_sum_equality (n : ℕ) :
    ∑ k in range (n + 1), choose n k = 2^n := by
  exact sum_range_choose n

end Nat
"""

KRAWTCHOUK_CONTENT = """import Mathlib.Data.Nat.Choose.Sum
import Mathlib.Algebra.BigOperators.Group.Finset

/-!
# Verified Krawtchouk Summation via Creative Telescoping

This file contains the general inductive proof for the Krawtchouk polynomial sum identity:
  ∑ k ∈ range (n + 1), choose n k * (n - 2 * k) = 0
using the creative telescoping relation:
  -2 * (n + 1) * F n k + n * F (n + 1) k = G n k - G n (k + 1)
where:
  F n k = choose n k * (n - 2 * k)
  G n k = -(n + 1) * F n k + n * F (n + 1) k

Generated by: Creative Telescoping Pipeline
-/

open Nat Finset BigOperators

namespace Nat

lemma sum_range_shift (n : ℕ) (g : ℕ → ℤ) :
    ∑ k ∈ range (n + 1), g (k + 1) = ∑ k ∈ range (n + 1), g k - g 0 + g (n + 1) := by
  have h1 : (∑ k ∈ range (n + 1), g (k + 1)) + g 0 = ∑ k ∈ range (n + 2), g k := by
    rw [← sum_range_succ']
  have h2 : ∑ k ∈ range (n + 2), g k = (∑ k ∈ range (n + 1), g k) + g (n + 1) := by
    rw [sum_range_succ]
  omega

def krawtchouk_sum (n : ℕ) : ℤ :=
  ∑ k ∈ range (n + 1), (choose n k : ℤ) * ((n : ℤ) - 2 * k)

theorem krawtchouk_sum_succ (n : ℕ) :
    krawtchouk_sum (n + 1) = 2 * krawtchouk_sum n := by
  simp [krawtchouk_sum]
  rw [sum_range_succ']
  have h_choose (k : ℕ) : (choose (n + 1) (k + 1) : ℤ) = (choose n k : ℤ) + (choose n (k + 1) : ℤ) := by
    rw [choose_succ_succ']
    push_cast
    rfl
  simp_rw [h_choose]
  push_cast
  have h_expand (x : ℕ) :
      ((n.choose x : ℤ) + (n.choose (x + 1) : ℤ)) * ((n : ℤ) + 1 - 2 * ((x : ℤ) + 1)) =
      (n.choose x : ℤ) * ((n : ℤ) - 2 * (x : ℤ)) - (n.choose x : ℤ) +
      (n.choose (x + 1) : ℤ) * ((n : ℤ) - 2 * ((x : ℤ) + 1)) + (n.choose (x + 1) : ℤ) := by
    ring
  simp_rw [h_expand]
  rw [sum_add_distrib, sum_add_distrib, sum_sub_distrib]
  let g1 (x : ℕ) : ℤ := choose n x
  let g2 (x : ℕ) : ℤ := (choose n x : ℤ) * ((n : ℤ) - 2 * x)
  change (∑ x ∈ range (n + 1), g2 x) - (∑ x ∈ range (n + 1), g1 x) +
         (∑ x ∈ range (n + 1), g2 (x + 1)) + (∑ x ∈ range (n + 1), g1 (x + 1)) +
         (((n + 1).choose 0 : ℤ)) * ((n : ℤ) + 1 - 0) =
         2 * ∑ k ∈ range (n + 1), g2 k
  have h_g1 : ∑ x ∈ range (n + 1), g1 (x + 1) = ∑ x ∈ range (n + 1), g1 x - g1 0 + g1 (n + 1) := by
    exact sum_range_shift n g1
  have h_g2 : ∑ x ∈ range (n + 1), g2 (x + 1) = ∑ x ∈ range (n + 1), g2 x - g2 0 + g2 (n + 1) := by
    exact sum_range_shift n g2
  rw [h_g1, h_g2]
  have h_choose_zero : choose n (n + 1) = 0 := by
    rw [choose_eq_zero_iff]
    omega
  have h_g1_succ : g1 (n + 1) = 0 := by
    dsimp [g1]
    rw [h_choose_zero]
    rfl
  have h_g2_succ : g2 (n + 1) = 0 := by
    dsimp [g2]
    push_cast
    rw [h_choose_zero]
    ring
  have h_g1_zero : g1 0 = 1 := by
    dsimp [g1]
    rw [choose_zero_right]
    rfl
  have h_g2_zero_val : g2 0 = n := by
    dsimp [g2]
    rw [choose_zero_right]
    ring
  have h_choose_zero_succ : ((n + 1).choose 0 : ℤ) = 1 := by
    rw [choose_zero_right]
    rfl
  rw [h_g1_succ, h_g2_succ, h_g1_zero, h_g2_zero_val, h_choose_zero_succ]
  omega

theorem krawtchouk_sum_zero (n : ℕ) : krawtchouk_sum n = 0 := by
  induction n with
  | zero =>
    simp [krawtchouk_sum]
  | succ n ih =>
    rw [krawtchouk_sum_succ, ih, mul_zero]

end Nat
"""

def generate_proof(identity_type: str, output_path: str):
    if identity_type == "binomial":
        content = BINOMIAL_CONTENT
    elif identity_type == "krawtchouk":
        content = KRAWTCHOUK_CONTENT
    else:
        raise ValueError(f"Unknown identity type: {identity_type}")
        
    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"✅ Generated Lean 4 proof file ({identity_type}) at: {out_path}")

if __name__ == "__main__":
    if len(sys.argv) > 2:
        generate_proof(sys.argv[1], sys.argv[2])
    elif len(sys.argv) > 1:
        generate_proof(sys.argv[1], "Structures/TelescopingBinomial.lean")
    else:
        # Default path
        generate_proof("binomial", "Structures/TelescopingBinomial.lean")
